name: 'AWS Action To Invoke Lambda By CoffeeBeansLabs'
description: This action is to invoke lambda with payload
author: CoffeeBeansLabs

# Define your inputs here.
inputs:
  lambda-name:
    description: Name of the lambda
    required: true
  payload:
    description: Payload in json structure or key value pairs like env.
    required: true
    default: '{}'

runs:
  using: docker
  image: Dockerfile
  env:
    INPUT_LAMBDA_NAME: ${{ inputs.lambda-name }}
    INPUT_PAYLOAD: ${{ inputs.payload }}
