name: test aws action for put parameter store
permissions:
  contents: write
  actions: write
on:
  push:
    branches:
      - temp
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: test lambda invoke
        uses: ./
        with:
          parameters: test=test
          lambda-name: test-lambda

      - name: test parameter store
        uses: ./
        with:
          parameters: |
            test=test
            test1=test1
            testing=testing2
          lambda-name: test-lambda

      - name: test parameter store
        uses: ./
        with:
          parameters: |
            {"test":"test",
            "test1":"test1",
            "testing":"testing2"}
          lambda-name: test-lambda